# Generated by Django 4.1 on 2022-08-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailingsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sending_status',
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('send', 'Send'), ('not send', 'Not send')], max_length=15, null=True),
        ),
    ]
